### ISSUE TITLE
有没有通用的

### ISSUE THREAD

**Issue by dataKingi** [ccdescipline/CInject#5]
想要能够自动获取其他windows的地址

**Comment by ccdescipline** [comment]
oxgenPdb

**Comment by dataKingi** [comment]
感谢，我还在调试bug...搜索的特征的时候会蓝屏
![1fef3e9c7592848a37409be995547af3](https://github.com/ccdescipline/CInject/assets/80020493/e852e03b-dc53-45ba-b6d4-5c94e10d58b2)
太奇怪了，明明匹配到了但是去执行了elseif...

**Comment by dataKingi** [comment]
解决了，居然要全部大写字母不然匹配不到

**Comment by dataKingi** [comment]
> oxgenPdb
我的物理机上运行会蓝屏...我需要帮助，qq：2696662105
