### ISSUE TITLE
error from no were

### ISSUE THREAD

**Issue by 4ksr** [ccdescipline/CInject#6]
Severity	Code	Description	Project	File	Line	Suppression State	Details
Error		No file digest algorithm specified. Please specify the digest algorithm with the /fd flag. Using /fd SHA256 is recommended and more secure than SHA1. Calling signtool with /fd sha1 is equivalent to the previous behavior. In order to select the hash algorithm used in the signing certificate's signature, use the /fd certHash option.	TestDriver	E:\F\c++\CInject-master\CInject-master\TestDriver\SIGNTASK	1

**Comment by pieewiee** [comment]
just disable test signing

**Comment by 4ksr** [comment]
> just disable test signing

i realy fix it but tk you man
